# Exercícios de revisão — Upload de arquivo, Pandas e NumPy

Nesta atividade, você vai usar a planilha **`base_exercicios_alunos_pandas.xlsx`** para praticar leitura de arquivo, exploração de dados, filtros, tratamento simples e uma introdução ao **NumPy**.

> Professor: você pode pedir que os alunos resolvam primeiro sozinhos e depois fazer a correção em sala.

## 1. Importando as bibliotecas

Use esta célula para importar as bibliotecas necessárias.

In [1]:
import pandas as pd
import numpy as np

## 2. Carregando o arquivo

Se estiver no **Google Colab**, primeiro envie a planilha.

Se estiver no **Jupyter Notebook**, basta garantir que o arquivo está na mesma pasta do notebook.

In [2]:
# Se estiver no Google Colab, descomente estas linhas:
# from google.colab import files
# uploaded = files.upload()

df = pd.read_excel("base_exercicios_alunos_pandas.xlsx")
df.head()

,id_aluno,nome,idade,turma,curso,nota1,nota2,faltas,cidade,uf,data_matricula,mensalidade,bolsista,email,status
0,1,Ana Clara,18.0,A,IA,8.5,9.0,2.0,Brasília,DF,2025-02-10,850.0,Sim,ana.clara@email.com,Ativo
1,2,Bruno Lima,20.0,A,Desenvolvimento,6.0,7.5,5.0,Goiânia,GO,2025-02-12,920.0,Não,bruno.lima@email.com,Ativo
2,3,Carla Souza,19.0,B,IA,9.2,NaN,1.0,Brasília,DF,2025-02-15,850.0,Sim,carla.souza@email.com,Ativo
3,4,Diego Alves,NaN,B,Dados,5.5,6.0,8.0,Anápolis,GO,2025-02-20,780.0,Não,diego.alves@email.com,Risco
4,5,Eduarda Melo,21.0,A,Dados,7.8,8.1,NaN,Taguatinga,DF,2025-02-18,780.0,Sim,eduarda.melo@email.com,Ativo

## 3. Conhecendo a base

### Exercício 1
Mostre as **5 primeiras linhas** da base.

### Exercício 2
Mostre as **5 últimas linhas** da base.

### Exercício 3
Descubra:
- quantidade de linhas e colunas
- nomes das colunas
- tipos de dados

In [3]:
df.head()

,id_aluno,nome,idade,turma,curso,nota1,nota2,faltas,cidade,uf,data_matricula,mensalidade,bolsista,email,status
0,1,Ana Clara,18.0,A,IA,8.5,9.0,2.0,Brasília,DF,2025-02-10,850.0,Sim,ana.clara@email.com,Ativo
1,2,Bruno Lima,20.0,A,Desenvolvimento,6.0,7.5,5.0,Goiânia,GO,2025-02-12,920.0,Não,bruno.lima@email.com,Ativo
2,3,Carla Souza,19.0,B,IA,9.2,NaN,1.0,Brasília,DF,2025-02-15,850.0,Sim,carla.souza@email.com,Ativo
3,4,Diego Alves,NaN,B,Dados,5.5,6.0,8.0,Anápolis,GO,2025-02-20,780.0,Não,diego.alves@email.com,Risco
4,5,Eduarda Melo,21.0,A,Dados,7.8,8.1,NaN,Taguatinga,DF,2025-02-18,780.0,Sim,eduarda.melo@email.com,Ativo

In [4]:
df.tail()

,id_aluno,nome,idade,turma,curso,nota1,nota2,faltas,cidade,uf,data_matricula,mensalidade,bolsista,email,status
25,26,Zeca Barros,24.0,C,Desenvolvimento,6.1,5.8,14.0,Goiânia,GO,2025-02-05,920.0,Não,zeca.barros@email.com,Risco
26,27,Ana Clara,18.0,A,IA,8.5,9.0,2.0,Brasília,DF,2025-02-10,850.0,Sim,ana.clara@email.com,Ativo
27,28,Beatriz Moura,20.0,B,NaN,7.2,7.6,4.0,Brasília,DF,2025-02-21,NaN,Sim,beatriz.moura@email.com,Ativo
28,29,Caio Moreira,19.0,C,Dados,NaN,NaN,NaN,NaN,NaN,2025-02-22,780.0,NaN,NaN,Ativo
29,30,Daniela Pires,22.0,B,Desenvolvimento,8.4,8.9,1.0,Brasília,DF,2025-02-11,920.0,sim,daniela.pires@email.com,Ativo

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 15 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   id_aluno        30 non-null     int64
 1   nome            30 non-null     str
 2   idade           28 non-null     float64
 3   turma           30 non-null     str
 4   curso           29 non-null     str
 5   nota1           28 non-null     float64
 6   nota2           27 non-null     float64
 7   faltas          28 non-null     float64
 8   cidade          29 non-null     str
 9   uf              29 non-null     str
 10  data_matricula  30 non-null     str
 11  mensalidade     29 non-null     float64
 12  bolsista        29 non-null     str
 13  email           28 non-null     str
 14  status          30 non-null     str
dtypes: float64(5), int64(1), str(9)
memory usage: 3.6 KB

## 4. Seleção de colunas

### Exercício 4
Mostre apenas as colunas:
- `nome`
- `curso`
- `turma`
- `nota1`

### Exercício 5
Crie um novo DataFrame chamado `df_notas` contendo:
- `nome`
- `nota1`
- `nota2`
- `faltas`

In [6]:
colunas = ["nome", "curso", "turma", "nota1"]
df[colunas].head()

           nome            curso turma  nota1
0     Ana Clara               IA     A    8.5
1    Bruno Lima  Desenvolvimento     A    6.0
2   Carla Souza               IA     B    9.2
3   Diego Alves            Dados     B    5.5
4  Eduarda Melo            Dados     A    7.8

In [7]:
colunas = ["nome", "nota1", "nota2", "faltas"]
df_notas = df[colunas]
df_notas.info()

<class 'pandas.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   nome    30 non-null     str
 1   nota1   28 non-null     float64
 2   nota2   27 non-null     float64
 3   faltas  28 non-null     float64
dtypes: float64(3), str(1)
memory usage: 1.1 KB

## 5. Filtros

### Exercício 6
Filtre apenas os alunos do curso **IA**.

### Exercício 7
Filtre apenas os alunos com `nota1` maior ou igual a **7**.

### Exercício 8
Filtre apenas os alunos da turma **B** e do curso **Dados**.

### Exercício 9
Filtre os alunos com mais de **5 faltas**.

In [8]:
# Alunos do Curso de IA
df[df['curso'] == "IA"]

,id_aluno,nome,idade,turma,curso,nota1,nota2,faltas,cidade,uf,data_matricula,mensalidade,bolsista,email,status
0,1,Ana Clara,18.0,A,IA,8.5,9.0,2.0,Brasília,DF,2025-02-10,850.0,Sim,ana.clara@email.com,Ativo
2,3,Carla Souza,19.0,B,IA,9.2,NaN,1.0,Brasília,DF,2025-02-15,850.0,Sim,carla.souza@email.com,Ativo
5,6,Felipe Rocha,22.0,C,IA,4.0,5.5,12.0,Luziânia,GO,2025-02-08,850.0,Não,felipe.rocha@email.com,Inativo
7,8,Henrique Silva,23.0,A,IA,NaN,7.9,3.0,Formosa,GO,2025-02-05,850.0,Nao,henrique.silva@email.com,Ativo
11,12,Lucas Matos,18.0,C,IA,3.5,4.5,15.0,Valparaíso,GO,2025-02-07,850.0,Não,NaN,Inativo
14,15,Olivia Martins,19.0,C,IA,10.0,9.8,0.0,Brasília,DF,2025-02-03,850.0,Sim,olivia.martins@email.com,Ativo
16,17,Quezia Araújo,23.0,B,IA,7.4,8.2,2.0,Brasília,DF,2025-02-17,850.0,Sim,quezia.araujo@email.com,Ativo
19,20,Thiago Mendes,21.0,C,IA,5.0,5.2,10.0,Águas Lindas,GO,2025-02-01,850.0,Não,thiago.mendes@email.com,Risco
22,23,Wesley Castro,20.0,B,IA,2.5,3.0,18.0,Brasília,DF,2025-02-02,850.0,Não,wesley.castro@email.com,Inativo
24,25,Yasmin Rocha,NaN,A,IA,8.3,8.7,2.0,Brasília,DF,2025-02-15,850.0,Sim,yasmin.rocha@email.com,Ativo
26,27,Ana Clara,18.0,A,IA,8.5,9.0,2.0,Brasília,DF,2025-02-10,850.0,Sim,ana.clara@email.com,Ativo

In [9]:
# Alunos com nota1 > 7
df[df['nota1'] >= 7]

,id_aluno,nome,idade,turma,curso,nota1,nota2,faltas,cidade,uf,data_matricula,mensalidade,bolsista,email,status
0,1,Ana Clara,18.0,A,IA,8.5,9.0,2.0,Brasília,DF,2025-02-10,850.0,Sim,ana.clara@email.com,Ativo
2,3,Carla Souza,19.0,B,IA,9.2,NaN,1.0,Brasília,DF,2025-02-15,850.0,Sim,carla.souza@email.com,Ativo
4,5,Eduarda Melo,21.0,A,Dados,7.8,8.1,NaN,Taguatinga,DF,2025-02-18,780.0,Sim,eduarda.melo@email.com,Ativo
6,7,Gabriela Nunes,18.0,C,Desenvolvimento,8.0,8.8,0.0,Brasília,DF,2025-02-09,920.0,SIM,gabriela.nunes@email.com,Ativo
8,9,Isabela Costa,20.0,B,Dados,9.5,9.7,1.0,Brasília,DF,2025-02-11,780.0,Sim,isabela.costa@email.com,Ativo
10,11,Karen Dias,24.0,B,Dados,7.0,7.0,6.0,brasília,df,2025-02-16,780.0,Sim,karen.dias@email.com,Ativo
12,13,Mariana Reis,21.0,A,Dados,8.8,9.1,2.0,Brasília,DF,2025-02-14,780.0,Sim,mariana.reis@email.com,Ativo
14,15,Olivia Martins,19.0,C,IA,10.0,9.8,0.0,Brasília,DF,2025-02-03,850.0,Sim,olivia.martins@email.com,Ativo
16,17,Quezia Araújo,23.0,B,IA,7.4,8.2,2.0,Brasília,DF,2025-02-17,850.0,Sim,quezia.araujo@email.com,Ativo
18,19,Sara Teixeira,18.0,A,Dados,7.9,8.0,3.0,Sobradinho,DF,2025-02-19,780.0,Sim,sara.teixeira@email.com,Ativo
20,21,Ursula Ferraz,22.0,B,Dados,8.1,8.3,1.0,Brasília,DF,2025-02-18,780.0,Sim,ursula.ferraz@email.com,Ativo
23,24,Ximena Duarte,21.0,C,Dados,9.1,9.0,0.0,Taguatinga,DF,2025-02-04,780.0,Sim,ximena.duarte@email.com,Ativo
24,25,Yasmin Rocha,NaN,A,IA,8.3,8.7,2.0,Brasília,DF,2025-02-15,850.0,Sim,yasmin.rocha@email.com,Ativo
26,27,Ana Clara,18.0,A,IA,8.5,9.0,2.0,Brasília,DF,2025-02-10,850.0,Sim,ana.clara@email.com,Ativo
27,28,Beatriz Moura,20.0,B,NaN,7.2,7.6,4.0,Brasília,DF,2025-02-21,NaN,Sim,beatriz.moura@email.com,Ativo
29,30,Daniela Pires,22.0,B,Desenvolvimento,8.4,8.9,1.0,Brasília,DF,2025-02-11,920.0,sim,daniela.pires@email.com,Ativo

In [10]:
filtro = (df['turma'] == 'B') & (df['curso'] == 'Dados')
df[filtro]

,id_aluno,nome,idade,turma,curso,nota1,nota2,faltas,cidade,uf,data_matricula,mensalidade,bolsista,email,status
3,4,Diego Alves,NaN,B,Dados,5.5,6.0,8.0,Anápolis,GO,2025-02-20,780.0,Não,diego.alves@email.com,Risco
8,9,Isabela Costa,20.0,B,Dados,9.5,9.7,1.0,Brasília,DF,2025-02-11,780.0,Sim,isabela.costa@email.com,Ativo
10,11,Karen Dias,24.0,B,Dados,7.0,7.0,6.0,brasília,df,2025-02-16,780.0,Sim,karen.dias@email.com,Ativo
20,21,Ursula Ferraz,22.0,B,Dados,8.1,8.3,1.0,Brasília,DF,2025-02-18,780.0,Sim,ursula.ferraz@email.com,Ativo

In [11]:
filtro = df['faltas'] > 5
df[filtro]

,id_aluno,nome,idade,turma,curso,nota1,nota2,faltas,cidade,uf,data_matricula,mensalidade,bolsista,email,status
3,4,Diego Alves,NaN,B,Dados,5.5,6.0,8.0,Anápolis,GO,2025-02-20,780.0,Não,diego.alves@email.com,Risco
5,6,Felipe Rocha,22.0,C,IA,4.0,5.5,12.0,Luziânia,GO,2025-02-08,850.0,Não,felipe.rocha@email.com,Inativo
10,11,Karen Dias,24.0,B,Dados,7.0,7.0,6.0,brasília,df,2025-02-16,780.0,Sim,karen.dias@email.com,Ativo
11,12,Lucas Matos,18.0,C,IA,3.5,4.5,15.0,Valparaíso,GO,2025-02-07,850.0,Não,NaN,Inativo
13,14,Nicolas Prado,20.0,B,Desenvolvimento,5.9,6.8,7.0,Gama,DF,2025-02-10,920.0,Não,nicolas.prado@email.com,Risco
15,16,Paulo Vitor,22.0,A,Dados,6.3,5.9,9.0,Cidade Ocidental,GO,2025-02-12,780.0,Não,paulo.vitor@email.com,Risco
17,18,Rafael Gomes,20.0,C,Desenvolvimento,4.8,NaN,11.0,Planaltina,DF,2025-02-06,920.0,Não,rafael.gomes@email.com,Inativo
19,20,Thiago Mendes,21.0,C,IA,5.0,5.2,10.0,Águas Lindas,GO,2025-02-01,850.0,Não,thiago.mendes@email.com,Risco
22,23,Wesley Castro,20.0,B,IA,2.5,3.0,18.0,Brasília,DF,2025-02-02,850.0,Não,wesley.castro@email.com,Inativo
25,26,Zeca Barros,24.0,C,Desenvolvimento,6.1,5.8,14.0,Goiânia,GO,2025-02-05,920.0,Não,zeca.barros@email.com,Risco

## 6. Valores nulos

### Exercício 10
Verifique quantos valores nulos existem em cada coluna.

### Exercício 11
Mostre apenas as linhas onde a coluna `idade` está nula.

### Exercício 12
Preencha os valores nulos de `nota1` com a média da coluna `nota1`.

In [12]:
df.isnull().sum()

id_aluno          0
nome              0
idade             2
turma             0
curso             1
nota1             2
nota2             3
faltas            2
cidade            1
uf                1
data_matricula    0
mensalidade       1
bolsista          1
email             2
status            0
dtype: int64

In [13]:
filtro = df['idade'].isnull()
df[filtro]

,id_aluno,nome,idade,turma,curso,nota1,nota2,faltas,cidade,uf,data_matricula,mensalidade,bolsista,email,status
3,4,Diego Alves,NaN,B,Dados,5.5,6.0,8.0,Anápolis,GO,2025-02-20,780.0,Não,diego.alves@email.com,Risco
24,25,Yasmin Rocha,NaN,A,IA,8.3,8.7,2.0,Brasília,DF,2025-02-15,850.0,Sim,yasmin.rocha@email.com,Ativo

In [14]:
media = df["nota1"].mean()
df['nota1'] = df["nota1"].fillna(media).round(2)
df["nota1"]

0      8.50
1      6.00
2      9.20
3      5.50
4      7.80
5      4.00
6      8.00
7      7.03
8      9.50
9      6.70
10     7.00
11     3.50
12     8.80
13     5.90
14    10.00
15     6.30
16     7.40
17     4.80
18     7.90
19     5.00
20     8.10
21     6.90
22     2.50
23     9.10
24     8.30
25     6.10
26     8.50
27     7.20
28     7.03
29     8.40
Name: nota1, dtype: float64

## 7. Tratamento de texto e padronização

### Exercício 13
Padronize a coluna `bolsista` para ficar apenas com:
- `Sim`
- `Não`

Dica: existem valores como `SIM`, `sim`, `Nao`.

### Exercício 14
Padronize a coluna `uf` para letras maiúsculas.

### Exercício 15
Padronize a coluna `cidade` no formato título.
Exemplo:
- `brasília` → `Brasília`

In [15]:
df['bolsista'] = df['bolsista'].str.capitalize()
df['bolsista']

0     Sim
1     Não
2     Sim
3     Não
4     Sim
5     Não
6     Sim
7     Nao
8     Sim
9     Não
10    Sim
11    Não
12    Sim
13    Não
14    Sim
15    Não
16    Sim
17    Não
18    Sim
19    Não
20    Sim
21    Não
22    Não
23    Sim
24    Sim
25    Não
26    Sim
27    Sim
28    NaN
29    Sim
Name: bolsista, dtype: str

In [16]:
df['uf'] = df['uf'].str.upper()
df['uf']

0      DF
1      GO
2      DF
3      GO
4      DF
5      GO
6      DF
7      GO
8      DF
9      GO
10     DF
11     GO
12     DF
13     DF
14     DF
15     GO
16     DF
17     DF
18     DF
19     GO
20     DF
21     GO
22     DF
23     DF
24     DF
25     GO
26     DF
27     DF
28    NaN
29     DF
Name: uf, dtype: str

In [17]:
df['cidade'] = df['cidade'].str.capitalize()
df['cidade']

0                 Brasília
1                  Goiânia
2                 Brasília
3                 Anápolis
4               Taguatinga
5                 Luziânia
6                 Brasília
7                  Formosa
8                 Brasília
9     Aparecida de goiânia
10                Brasília
11              Valparaíso
12                Brasília
13                    Gama
14                Brasília
15        Cidade ocidental
16                Brasília
17              Planaltina
18              Sobradinho
19            Águas lindas
20                Brasília
21                 Goiânia
22                Brasília
23              Taguatinga
24                Brasília
25                 Goiânia
26                Brasília
27                Brasília
28                     NaN
29                Brasília
Name: cidade, dtype: str

## 8. Criando novas colunas

### Exercício 16
Crie uma coluna chamada `media` com a média entre `nota1` e `nota2`.

### Exercício 17
Crie uma coluna chamada `aprovado`:
- `True` para média maior ou igual a **7**
- `False` caso contrário

### Exercício 18
Crie uma coluna chamada `situacao_faltas`:
- `Alto risco` para mais de 10 faltas
- `Atenção` para 6 a 10 faltas
- `Ok` para até 5 faltas

In [18]:
df['nota1'] = df['nota1'].fillna(0)
df['nota2'] = df['nota2'].fillna(0)
df['media'] = ((df['nota1'] + df['nota2']) / 2).round(2)
df

,id_aluno,nome,idade,turma,curso,nota1,nota2,faltas,cidade,uf,data_matricula,mensalidade,bolsista,email,status,media
0,1,Ana Clara,18.0,A,IA,8.50,9.0,2.0,Brasília,DF,2025-02-10,850.0,Sim,ana.clara@email.com,Ativo,8.75
1,2,Bruno Lima,20.0,A,Desenvolvimento,6.00,7.5,5.0,Goiânia,GO,2025-02-12,920.0,Não,bruno.lima@email.com,Ativo,6.75
2,3,Carla Souza,19.0,B,IA,9.20,0.0,1.0,Brasília,DF,2025-02-15,850.0,Sim,carla.souza@email.com,Ativo,4.60
3,4,Diego Alves,NaN,B,Dados,5.50,6.0,8.0,Anápolis,GO,2025-02-20,780.0,Não,diego.alves@email.com,Risco,5.75
4,5,Eduarda Melo,21.0,A,Dados,7.80,8.1,NaN,Taguatinga,DF,2025-02-18,780.0,Sim,eduarda.melo@email.com,Ativo,7.95
5,6,Felipe Rocha,22.0,C,IA,4.00,5.5,12.0,Luziânia,GO,2025-02-08,850.0,Não,felipe.rocha@email.com,Inativo,4.75
6,7,Gabriela Nunes,18.0,C,Desenvolvimento,8.00,8.8,0.0,Brasília,DF,2025-02-09,920.0,Sim,gabriela.nunes@email.com,Ativo,8.40
7,8,Henrique Silva,23.0,A,IA,7.03,7.9,3.0,Formosa,GO,2025-02-05,850.0,Nao,henrique.silva@email.com,Ativo,7.46
8,9,Isabela Costa,20.0,B,Dados,9.50,9.7,1.0,Brasília,DF,2025-02-11,780.0,Sim,isabela.costa@email.com,Ativo,9.60
9,10,João Pedro,19.0,A,Desenvolvimento,6.70,6.2,4.0,Aparecida de goiânia,GO,2025-02-13,920.0,Não,joao.pedro@email,Risco,6.45
10,11,Karen Dias,24.0,B,Dados,7.00,7.0,6.0,Brasília,DF,2025-02-16,780.0,Sim,karen.dias@email.com,Ativo,7.00
11,12,Lucas Matos,18.0,C,IA,3.50,4.5,15.0,Valparaíso,GO,2025-02-07,850.0,Não,NaN,Inativo,4.00
12,13,Mariana Reis,21.0,A,Dados,8.80,9.1,2.0,Brasília,DF,2025-02-14,780.0,Sim,mariana.reis@email.com,Ativo,8.95
13,14,Nicolas Prado,20.0,B,Desenvolvimento,5.90,6.8,7.0,Gama,DF,2025-02-10,920.0,Não,nicolas.prado@email.com,Risco,6.35
14,15,Olivia Martins,19.0,C,IA,10.00,9.8,0.0,Brasília,DF,2025-02-03,850.0,Sim,olivia.martins@email.com,Ativo,9.90
15,16,Paulo Vitor,22.0,A,Dados,6.30,5.9,9.0,Cidade ocidental,GO,2025-02-12,780.0,Não,paulo.vitor@email.com,Risco,6.10
16,17,Quezia Araújo,23.0,B,IA,7.40,8.2,2.0,Brasília,DF,2025-02-17,850.0,Sim,quezia.araujo@email.com,Ativo,7.80
17,18,Rafael Gomes,20.0,C,Desenvolvimento,4.80,0.0,11.0,Planaltina,DF,2025-02-06,920.0,Não,rafael.gomes@email.com,Inativo,2.40
18,19,Sara Teixeira,18.0,A,Dados,7.90,8.0,3.0,Sobradinho,DF,2025-02-19,780.0,Sim,sara.teixeira@email.com,Ativo,7.95
19,20,Thiago Mendes,21.0,C,IA,5.00,5.2,10.0,Águas lindas,GO,2025-02-01,850.0,Não,thiago.mendes@email.com,Risco,5.10
20,21,Ursula Ferraz,22.0,B,Dados,8.10,8.3,1.0,Brasília,DF,2025-02-18,780.0,Sim,ursula.ferraz@email.com,Ativo,8.20
21,22,Vinicius Lopes,19.0,A,Desenvolvimento,6.90,7.1,5.0,Goiânia,GO,2025-02-20,920.0,Não,vinicius.lopes@email.com,Ativo,7.00
22,23,Wesley Castro,20.0,B,IA,2.50,3.0,18.0,Brasília,DF,2025-02-02,850.0,Não,wesley.castro@email.com,Inativo,2.75
23,24,Ximena Duarte,21.0,C,Dados,9.10,9.0,0.0,Taguatinga,DF,2025-02-04,780.0,Sim,ximena.duarte@email.com,Ativo,9.05
24,25,Yasmin Rocha,NaN,A,IA,8.30,8.7,2.0,Brasília,DF,2025-02-15,850.0,Sim,yasmin.rocha@email.com,Ativo,8.50
25,26,Zeca Barros,24.0,C,Desenvolvimento,6.10,5.8,14.0,Goiânia,GO,2025-02-05,920.0,Não,zeca.barros@email.com,Risco,5.95
26,27,Ana Clara,18.0,A,IA,8.50,9.0,2.0,Brasília,DF,2025-02-10,850.0,Sim,ana.clara@email.com,Ativo,8.75
27,28,Beatriz Moura,20.0,B,NaN,7.20,7.6,4.0,Brasília,DF,2025-02-21,NaN,Sim,beatriz.moura@email.com,Ativo,7.40
28,29,Caio Moreira,19.0,C,Dados,7.03,0.0,NaN,NaN,NaN,2025-02-22,780.0,NaN,NaN,Ativo,3.52
29,30,Daniela Pires,22.0,B,Desenvolvimento,8.40,8.9,1.0,Brasília,DF,2025-02-11,920.0,Sim,daniela.pires@email.com,Ativo,8.65

In [19]:

df['aprovado'] = df['media'] >= 7
df.head(10)

,id_aluno,nome,idade,turma,curso,nota1,nota2,faltas,cidade,uf,data_matricula,mensalidade,bolsista,email,status,media,aprovado
0,1,Ana Clara,18.0,A,IA,8.50,9.0,2.0,Brasília,DF,2025-02-10,850.0,Sim,ana.clara@email.com,Ativo,8.75,True
1,2,Bruno Lima,20.0,A,Desenvolvimento,6.00,7.5,5.0,Goiânia,GO,2025-02-12,920.0,Não,bruno.lima@email.com,Ativo,6.75,False
2,3,Carla Souza,19.0,B,IA,9.20,0.0,1.0,Brasília,DF,2025-02-15,850.0,Sim,carla.souza@email.com,Ativo,4.60,False
3,4,Diego Alves,NaN,B,Dados,5.50,6.0,8.0,Anápolis,GO,2025-02-20,780.0,Não,diego.alves@email.com,Risco,5.75,False
4,5,Eduarda Melo,21.0,A,Dados,7.80,8.1,NaN,Taguatinga,DF,2025-02-18,780.0,Sim,eduarda.melo@email.com,Ativo,7.95,True
5,6,Felipe Rocha,22.0,C,IA,4.00,5.5,12.0,Luziânia,GO,2025-02-08,850.0,Não,felipe.rocha@email.com,Inativo,4.75,False
6,7,Gabriela Nunes,18.0,C,Desenvolvimento,8.00,8.8,0.0,Brasília,DF,2025-02-09,920.0,Sim,gabriela.nunes@email.com,Ativo,8.40,True
7,8,Henrique Silva,23.0,A,IA,7.03,7.9,3.0,Formosa,GO,2025-02-05,850.0,Nao,henrique.silva@email.com,Ativo,7.46,True
8,9,Isabela Costa,20.0,B,Dados,9.50,9.7,1.0,Brasília,DF,2025-02-11,780.0,Sim,isabela.costa@email.com,Ativo,9.60,True
9,10,João Pedro,19.0,A,Desenvolvimento,6.70,6.2,4.0,Aparecida de goiânia,GO,2025-02-13,920.0,Não,joao.pedro@email,Risco,6.45,False

In [20]:
"""import numpy as np

condicoes = [
    (df['faltas'] > 10),
    (df['faltas'] > 5) & (df['faltas'] <= 10),
    (df['faltas'] >= 0) & (df['faltas'] <= 5)
]

classificacao = ["Alto risco", "Atenção", "Ok"]

df['situacao_faltas'] = np.select(condicoes, classificacao, default="Indefinido")
df.head()
"""
def situacao_faltas(faltas):
    if faltas > 10:
        return "Alto risco"
    elif 5 < faltas <= 10:
        return "Atenção"
    elif 0 <= faltas <= 5:
        return "Ok"
    else:
        return "Indefinido"

df['situacao_faltas'] = df['faltas'].apply(situacao_faltas)
df.head()

,id_aluno,nome,idade,turma,curso,nota1,nota2,faltas,cidade,uf,data_matricula,mensalidade,bolsista,email,status,media,aprovado,situacao_faltas
0,1,Ana Clara,18.0,A,IA,8.5,9.0,2.0,Brasília,DF,2025-02-10,850.0,Sim,ana.clara@email.com,Ativo,8.75,True,Ok
1,2,Bruno Lima,20.0,A,Desenvolvimento,6.0,7.5,5.0,Goiânia,GO,2025-02-12,920.0,Não,bruno.lima@email.com,Ativo,6.75,False,Ok
2,3,Carla Souza,19.0,B,IA,9.2,0.0,1.0,Brasília,DF,2025-02-15,850.0,Sim,carla.souza@email.com,Ativo,4.60,False,Ok
3,4,Diego Alves,NaN,B,Dados,5.5,6.0,8.0,Anápolis,GO,2025-02-20,780.0,Não,diego.alves@email.com,Risco,5.75,False,Atenção
4,5,Eduarda Melo,21.0,A,Dados,7.8,8.1,NaN,Taguatinga,DF,2025-02-18,780.0,Sim,eduarda.melo@email.com,Ativo,7.95,True,Indefinido

## 9. Ordenação, contagem e agrupamento

### Exercício 19
Ordene os alunos pela coluna `media`, do maior para o menor.

### Exercício 20
Conte quantos alunos existem em cada curso.

### Exercício 21
Mostre a média de `nota1` por curso.

### Exercício 22
Mostre a média de faltas por turma.

In [21]:
df.sort_values(by='media', ascending=False)

,id_aluno,nome,idade,turma,curso,nota1,nota2,faltas,cidade,uf,data_matricula,mensalidade,bolsista,email,status,media,aprovado,situacao_faltas
14,15,Olivia Martins,19.0,C,IA,10.00,9.8,0.0,Brasília,DF,2025-02-03,850.0,Sim,olivia.martins@email.com,Ativo,9.90,True,Ok
8,9,Isabela Costa,20.0,B,Dados,9.50,9.7,1.0,Brasília,DF,2025-02-11,780.0,Sim,isabela.costa@email.com,Ativo,9.60,True,Ok
23,24,Ximena Duarte,21.0,C,Dados,9.10,9.0,0.0,Taguatinga,DF,2025-02-04,780.0,Sim,ximena.duarte@email.com,Ativo,9.05,True,Ok
12,13,Mariana Reis,21.0,A,Dados,8.80,9.1,2.0,Brasília,DF,2025-02-14,780.0,Sim,mariana.reis@email.com,Ativo,8.95,True,Ok
0,1,Ana Clara,18.0,A,IA,8.50,9.0,2.0,Brasília,DF,2025-02-10,850.0,Sim,ana.clara@email.com,Ativo,8.75,True,Ok
26,27,Ana Clara,18.0,A,IA,8.50,9.0,2.0,Brasília,DF,2025-02-10,850.0,Sim,ana.clara@email.com,Ativo,8.75,True,Ok
29,30,Daniela Pires,22.0,B,Desenvolvimento,8.40,8.9,1.0,Brasília,DF,2025-02-11,920.0,Sim,daniela.pires@email.com,Ativo,8.65,True,Ok
24,25,Yasmin Rocha,NaN,A,IA,8.30,8.7,2.0,Brasília,DF,2025-02-15,850.0,Sim,yasmin.rocha@email.com,Ativo,8.50,True,Ok
6,7,Gabriela Nunes,18.0,C,Desenvolvimento,8.00,8.8,0.0,Brasília,DF,2025-02-09,920.0,Sim,gabriela.nunes@email.com,Ativo,8.40,True,Ok
20,21,Ursula Ferraz,22.0,B,Dados,8.10,8.3,1.0,Brasília,DF,2025-02-18,780.0,Sim,ursula.ferraz@email.com,Ativo,8.20,True,Ok
4,5,Eduarda Melo,21.0,A,Dados,7.80,8.1,NaN,Taguatinga,DF,2025-02-18,780.0,Sim,eduarda.melo@email.com,Ativo,7.95,True,Indefinido
18,19,Sara Teixeira,18.0,A,Dados,7.90,8.0,3.0,Sobradinho,DF,2025-02-19,780.0,Sim,sara.teixeira@email.com,Ativo,7.95,True,Ok
16,17,Quezia Araújo,23.0,B,IA,7.40,8.2,2.0,Brasília,DF,2025-02-17,850.0,Sim,quezia.araujo@email.com,Ativo,7.80,True,Ok
7,8,Henrique Silva,23.0,A,IA,7.03,7.9,3.0,Formosa,GO,2025-02-05,850.0,Nao,henrique.silva@email.com,Ativo,7.46,True,Ok
27,28,Beatriz Moura,20.0,B,NaN,7.20,7.6,4.0,Brasília,DF,2025-02-21,NaN,Sim,beatriz.moura@email.com,Ativo,7.40,True,Ok
21,22,Vinicius Lopes,19.0,A,Desenvolvimento,6.90,7.1,5.0,Goiânia,GO,2025-02-20,920.0,Não,vinicius.lopes@email.com,Ativo,7.00,True,Ok
10,11,Karen Dias,24.0,B,Dados,7.00,7.0,6.0,Brasília,DF,2025-02-16,780.0,Sim,karen.dias@email.com,Ativo,7.00,True,Atenção
1,2,Bruno Lima,20.0,A,Desenvolvimento,6.00,7.5,5.0,Goiânia,GO,2025-02-12,920.0,Não,bruno.lima@email.com,Ativo,6.75,False,Ok
9,10,João Pedro,19.0,A,Desenvolvimento,6.70,6.2,4.0,Aparecida de goiânia,GO,2025-02-13,920.0,Não,joao.pedro@email,Risco,6.45,False,Ok
13,14,Nicolas Prado,20.0,B,Desenvolvimento,5.90,6.8,7.0,Gama,DF,2025-02-10,920.0,Não,nicolas.prado@email.com,Risco,6.35,False,Atenção
15,16,Paulo Vitor,22.0,A,Dados,6.30,5.9,9.0,Cidade ocidental,GO,2025-02-12,780.0,Não,paulo.vitor@email.com,Risco,6.10,False,Atenção
25,26,Zeca Barros,24.0,C,Desenvolvimento,6.10,5.8,14.0,Goiânia,GO,2025-02-05,920.0,Não,zeca.barros@email.com,Risco,5.95,False,Alto risco
3,4,Diego Alves,NaN,B,Dados,5.50,6.0,8.0,Anápolis,GO,2025-02-20,780.0,Não,diego.alves@email.com,Risco,5.75,False,Atenção
19,20,Thiago Mendes,21.0,C,IA,5.00,5.2,10.0,Águas lindas,GO,2025-02-01,850.0,Não,thiago.mendes@email.com,Risco,5.10,False,Atenção
5,6,Felipe Rocha,22.0,C,IA,4.00,5.5,12.0,Luziânia,GO,2025-02-08,850.0,Não,felipe.rocha@email.com,Inativo,4.75,False,Alto risco
2,3,Carla Souza,19.0,B,IA,9.20,0.0,1.0,Brasília,DF,2025-02-15,850.0,Sim,carla.souza@email.com,Ativo,4.60,False,Ok
11,12,Lucas Matos,18.0,C,IA,3.50,4.5,15.0,Valparaíso,GO,2025-02-07,850.0,Não,NaN,Inativo,4.00,False,Alto risco
28,29,Caio Moreira,19.0,C,Dados,7.03,0.0,NaN,NaN,NaN,2025-02-22,780.0,NaN,NaN,Ativo,3.52,False,Indefinido
22,23,Wesley Castro,20.0,B,IA,2.50,3.0,18.0,Brasília,DF,2025-02-02,850.0,Não,wesley.castro@email.com,Inativo,2.75,False,Alto risco
17,18,Rafael Gomes,20.0,C,Desenvolvimento,4.80,0.0,11.0,Planaltina,DF,2025-02-06,920.0,Não,rafael.gomes@email.com,Inativo,2.40,False,Alto risco

In [22]:
df['curso'].value_counts(dropna=False)

curso
IA                 11
Dados              10
Desenvolvimento     8
NaN                 1
Name: count, dtype: int64

In [23]:
# Valor médio de nota1 para cada curso
df.groupby("curso")['nota1'].mean().round(2)

curso
Dados              7.70
Desenvolvimento    6.60
IA                 6.72
Name: nota1, dtype: float64

In [24]:
# Média de faltas por turma
df.groupby("turma")['faltas'].mean()

turma
A    3.70
B    4.90
C    7.75
Name: faltas, dtype: float64

## 10. Duplicatas e qualidade dos dados

### Exercício 23
Verifique se existem linhas duplicadas.

### Exercício 24
Remova as duplicatas e salve em um novo DataFrame chamado `df_limpo`.

### Exercício 25
Mostre os registros com emails possivelmente inválidos.
Dica: procure emails sem `@` ou sem `.com`.

In [25]:
qtd_linhas_duplicadas = df.duplicated().sum()
print(f"Total de linhas duplicadas: {qtd_linhas_duplicadas}")

Total de linhas duplicadas: 0

In [26]:
# Caso houvessem linhas duplicadas
df_limpo = df.drop_duplicates()

In [27]:
# Este padrão exige: texto + @ + texto + . + extensão
padrao_email = r'^[\w\.-]+@[\w\.-]+\.\w+$'

filtro = ~df['email'].str.contains(padrao_email, na=False)
df[filtro]

,id_aluno,nome,idade,turma,curso,nota1,nota2,faltas,cidade,uf,data_matricula,mensalidade,bolsista,email,status,media,aprovado,situacao_faltas
9,10,João Pedro,19.0,A,Desenvolvimento,6.70,6.2,4.0,Aparecida de goiânia,GO,2025-02-13,920.0,Não,joao.pedro@email,Risco,6.45,False,Ok
11,12,Lucas Matos,18.0,C,IA,3.50,4.5,15.0,Valparaíso,GO,2025-02-07,850.0,Não,NaN,Inativo,4.00,False,Alto risco
28,29,Caio Moreira,19.0,C,Dados,7.03,0.0,NaN,NaN,NaN,2025-02-22,780.0,NaN,NaN,Ativo,3.52,False,Indefinido

## 11. Salvando um novo arquivo

### Exercício 26
Salve o DataFrame tratado em um novo arquivo Excel chamado:
`base_tratada_alunos.xlsx`

In [28]:
df.to_excel("base_tratada_alunos.xlsx", index=False)

## 12. Introdução ao NumPy

### Exercício 27
Crie um array NumPy com os valores da coluna `nota1`, removendo os nulos.

### Exercício 28
Com esse array, calcule:
- média
- maior valor
- menor valor
- soma

### Exercício 29
Some **1 ponto** em todas as notas do array.

### Exercício 30
Mostre apenas as notas maiores que **7** usando NumPy.

In [29]:
import numpy as np

nota1 = np.array(df['nota1'])

media = nota1.mean()
maior_valor = nota1.max()
menor_valor = nota1.min()
soma_notas = nota1.sum()

print("Media:", media)
print("Maior nota:", maior_valor)
print("Menor nota:", menor_valor)
print("Soma das notas:", soma_notas)

Media: 7.032
Maior nota: 10.0
Menor nota: 2.5
Soma das notas: 210.96

In [30]:
print("Antes:", nota1)
nota1 = nota1 + 1
nota1[nota1 > 10] = 10
print("Depois:", nota1)

Antes: [ 8.5   6.    9.2   5.5   7.8   4.    8.    7.03  9.5   6.7   7.    3.5
  8.8   5.9  10.    6.3   7.4   4.8   7.9   5.    8.1   6.9   2.5   9.1
  8.3   6.1   8.5   7.2   7.03  8.4 ]
Depois: [ 9.5   7.   10.    6.5   8.8   5.    9.    8.03 10.    7.7   8.    4.5
  9.8   6.9  10.    7.3   8.4   5.8   8.9   6.    9.1   7.9   3.5  10.
  9.3   7.1   9.5   8.2   8.03  9.4 ]

In [31]:
nota1[nota1 > 7]

array([ 9.5 , 10.  ,  8.8 ,  9.  ,  8.03, 10.  ,  7.7 ,  8.  ,  9.8 ,
       10.  ,  7.3 ,  8.4 ,  8.9 ,  9.1 ,  7.9 , 10.  ,  9.3 ,  7.1 ,
        9.5 ,  8.2 ,  8.03,  9.4 ])

## 13. Desafio final

### Exercício 31 — Desafio
Monte uma análise final respondendo:

1. Quantos alunos há em cada curso?
2. Qual curso tem a maior média de `nota1`?
3. Quantos alunos têm mais de 10 faltas?
4. Quantos alunos são bolsistas?
5. Há dados faltando? Em quais colunas?
6. Há duplicatas?
7. Gere um DataFrame final apenas com:
   - `nome`
   - `curso`
   - `media`
   - `aprovado`

Depois, ordene esse DataFrame pela `media` em ordem decrescente.

In [32]:
df['curso'].value_counts(dropna=False)

curso
IA                 11
Dados              10
Desenvolvimento     8
NaN                 1
Name: count, dtype: int64

In [33]:
df.groupby('curso')['nota1'].mean().sort_values(ascending=False).iloc[[0]]

curso
Dados    7.703
Name: nota1, dtype: float64

In [34]:
numero_alunos_10_faltas_mais = len(df[df['faltas'] > 10])
print(f"Quantidade de aluno com mais de dez faltas: {numero_alunos_10_faltas_mais}")

df[df['faltas'] > 10][['nome', 'faltas']]

Quantidade de aluno com mais de dez faltas: 5

             nome  faltas
5    Felipe Rocha    12.0
11    Lucas Matos    15.0
17   Rafael Gomes    11.0
22  Wesley Castro    18.0
25    Zeca Barros    14.0

In [35]:
qtd_bolsistas = len(df[df['bolsista'] == "Sim"])
print("Quantidade de bolsistas:", qtd_bolsistas)
df[df['bolsista'] == "Sim"][["nome", "bolsista"]]

Quantidade de bolsistas: 16

              nome bolsista
0        Ana Clara      Sim
2      Carla Souza      Sim
4     Eduarda Melo      Sim
6   Gabriela Nunes      Sim
8    Isabela Costa      Sim
10      Karen Dias      Sim
12    Mariana Reis      Sim
14  Olivia Martins      Sim
16   Quezia Araújo      Sim
18   Sara Teixeira      Sim
20   Ursula Ferraz      Sim
23   Ximena Duarte      Sim
24    Yasmin Rocha      Sim
26       Ana Clara      Sim
27   Beatriz Moura      Sim
29   Daniela Pires      Sim

In [36]:
df.isnull().sum()

id_aluno           0
nome               0
idade              2
turma              0
curso              1
nota1              0
nota2              0
faltas             2
cidade             1
uf                 1
data_matricula     0
mensalidade        1
bolsista           1
email              2
status             0
media              0
aprovado           0
situacao_faltas    0
dtype: int64

In [37]:
qtd_linhas_duplicadas = df.duplicated().sum()
contains_duplicated = qtd_linhas_duplicadas > 0

if contains_duplicated:
    print("Quantidade de linhas duplicadas:", qtd_linhas_duplicadas)
else:
    print("Não há linhas duplicadas.")

Não há linhas duplicadas.

In [38]:
colunas = ["nome", "curso", "media", "aprovado"]
novo_df = df[colunas].sort_values(by=['curso', 'media', 'aprovado'], ascending=False)
novo_df

              nome            curso  media  aprovado
14  Olivia Martins               IA   9.90      True
0        Ana Clara               IA   8.75      True
26       Ana Clara               IA   8.75      True
24    Yasmin Rocha               IA   8.50      True
16   Quezia Araújo               IA   7.80      True
7   Henrique Silva               IA   7.46      True
19   Thiago Mendes               IA   5.10     False
5     Felipe Rocha               IA   4.75     False
2      Carla Souza               IA   4.60     False
11     Lucas Matos               IA   4.00     False
22   Wesley Castro               IA   2.75     False
29   Daniela Pires  Desenvolvimento   8.65      True
6   Gabriela Nunes  Desenvolvimento   8.40      True
21  Vinicius Lopes  Desenvolvimento   7.00      True
1       Bruno Lima  Desenvolvimento   6.75     False
9       João Pedro  Desenvolvimento   6.45     False
13   Nicolas Prado  Desenvolvimento   6.35     False
25     Zeca Barros  Desenvolvimento   5.95     False
17    Rafael Gomes  Desenvolvimento   2.40     False
8    Isabela Costa            Dados   9.60      True
23   Ximena Duarte            Dados   9.05      True
12    Mariana Reis            Dados   8.95      True
20   Ursula Ferraz            Dados   8.20      True
4     Eduarda Melo            Dados   7.95      True
18   Sara Teixeira            Dados   7.95      True
10      Karen Dias            Dados   7.00      True
15     Paulo Vitor            Dados   6.10     False
3      Diego Alves            Dados   5.75     False
28    Caio Moreira            Dados   3.52     False
27   Beatriz Moura              NaN   7.40      True

## 14. Espaço para correção

Professor: aqui você pode ir resolvendo os exercícios em sala após os alunos tentarem.

In [39]:
# Correção do professor